In [1]:
import tensorflow as tf
print(tf.__version__)

2.16.1


In [2]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [13]:
### Vocabulary size
voc_size = 10000

______

### One Hot Representation

______

In [14]:
onehot_repr = [one_hot(words, voc_size) for words in sent] 
print(onehot_repr)

[[7957, 6194, 5469, 6920], [7957, 6194, 5469, 5558], [7957, 4085, 5469, 6303], [2024, 6986, 9646, 8353, 7395], [2024, 6986, 9646, 8353, 3699], [2701, 7957, 488, 5469, 1128], [4870, 846, 4052, 8353]]


_____

### Word Embedding Representation

_____

In [15]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

import numpy as np

In [16]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7957 6194 5469 6920]
 [   0    0    0    0 7957 6194 5469 5558]
 [   0    0    0    0 7957 4085 5469 6303]
 [   0    0    0 2024 6986 9646 8353 7395]
 [   0    0    0 2024 6986 9646 8353 3699]
 [   0    0    0 2701 7957  488 5469 1128]
 [   0    0    0    0 4870  846 4052 8353]]


In [65]:
## post padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7957 6194 5469 6920]
 [   0    0    0    0 7957 6194 5469 5558]
 [   0    0    0    0 7957 4085 5469 6303]
 [   0    0    0 2024 6986 9646 8353 7395]
 [   0    0    0 2024 6986 9646 8353 3699]
 [   0    0    0 2701 7957  488 5469 1128]
 [   0    0    0    0 4870  846 4052 8353]]


In [66]:
## 10 feature dimesnions
dim=10

In [79]:
model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=10, input_shape=(sent_length, )))
model.compile('adam','mse') 

In [80]:
model.summary()

Model: "sequential_19"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_16 (Embedding)        │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [81]:
## 'the glass of milk'

embedded_docs[0]

array([   0,    0,    0,    0, 7957, 6194, 5469, 6920], dtype=int32)

In [82]:
%%time
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
CPU times: user 68.3 ms, sys: 5.85 ms, total: 74.1 ms
Wall time: 71.3 ms


array([[[ 1.4615420e-02, -8.9096539e-03,  3.5221625e-02,  4.1341756e-02,
          4.6904683e-03,  3.7545409e-02, -1.1902966e-02, -4.1882314e-02,
          2.8792273e-02,  4.7993612e-02],
        [ 1.4615420e-02, -8.9096539e-03,  3.5221625e-02,  4.1341756e-02,
          4.6904683e-03,  3.7545409e-02, -1.1902966e-02, -4.1882314e-02,
          2.8792273e-02,  4.7993612e-02],
        [ 1.4615420e-02, -8.9096539e-03,  3.5221625e-02,  4.1341756e-02,
          4.6904683e-03,  3.7545409e-02, -1.1902966e-02, -4.1882314e-02,
          2.8792273e-02,  4.7993612e-02],
        [ 1.4615420e-02, -8.9096539e-03,  3.5221625e-02,  4.1341756e-02,
          4.6904683e-03,  3.7545409e-02, -1.1902966e-02, -4.1882314e-02,
          2.8792273e-02,  4.7993612e-02],
        [-1.1967111e-02, -2.2010792e-02, -6.2325597e-03, -1.1073574e-03,
         -4.4424187e-02,  1.9391291e-03, -3.5593286e-03,  3.8151924e-02,
          4.7585368e-03,  1.0503076e-02],
        [ 1.9931685e-02, -3.3692136e-02, -9.0840347e-03, -8.

In [83]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
[[ 0.01461542 -0.00890965  0.03522163  0.04134176  0.00469047  0.03754541
  -0.01190297 -0.04188231  0.02879227  0.04799361]
 [ 0.01461542 -0.00890965  0.03522163  0.04134176  0.00469047  0.03754541
  -0.01190297 -0.04188231  0.02879227  0.04799361]
 [ 0.01461542 -0.00890965  0.03522163  0.04134176  0.00469047  0.03754541
  -0.01190297 -0.04188231  0.02879227  0.04799361]
 [ 0.01461542 -0.00890965  0.03522163  0.04134176  0.00469047  0.03754541
  -0.01190297 -0.04188231  0.02879227  0.04799361]
 [-0.01196711 -0.02201079 -0.00623256 -0.00110736 -0.04442419  0.00193913
  -0.00355933  0.03815192  0.00475854  0.01050308]
 [ 0.01993169 -0.03369214 -0.00908403 -0.00850129 -0.02220967 -0.02713401
  -0.03691263  0.03181789  0.01745139  0.04865897]
 [ 0.03888918 -0.01364534  0.02766811  0.00147712  0.0410198   0.02568885
  -0.04695206  0.00648351 -0.02687494  0.02644681]
 [-0.01475413 -0.03767081  0.00011413  0.04496527  0.00422233  0.03590709
   0.03999728